/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.eatlog.common.model.eatlog.routines;


import com.github.mbto.eatlog.common.model.eatlog.Eatlog;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FindGeonameIdByIp extends AbstractRoutine<UInteger> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>eatlog.find_geoname_id_by_ip.RETURN_VALUE</code>.
     */
    public static final Parameter<UInteger> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.INTEGERUNSIGNED, false, false);

    /**
     * The parameter <code>eatlog.find_geoname_id_by_ip.ip</code>.
     */
    public static final Parameter<String> IP = Internal.createParameter("ip", SQLDataType.VARCHAR(15), false, false);

    /**
     * Create a new routine call instance
     */
    public FindGeonameIdByIp() {
        super("find_geoname_id_by_ip", Eatlog.EATLOG, SQLDataType.INTEGERUNSIGNED);

        setReturnParameter(RETURN_VALUE);
        addInParameter(IP);
    }

    /**
     * Set the <code>ip</code> parameter IN value to the routine
     */
    public void setIp(String value) {
        setValue(IP, value);
    }

    /**
     * Set the <code>ip</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public void setIp(Field<String> field) {
        setField(IP, field);
    }
}
