/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.eatlog.common.model.eatlog.tables.records;


import com.github.mbto.eatlog.common.model.eatlog.tables.Account;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;
import java.util.TreeSet;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountRecord extends UpdatableRecordImpl<AccountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>eatlog.account.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>eatlog.account.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>eatlog.account.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>eatlog.account.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>eatlog.account.lastauth_at</code>.
     */
    public void setLastauthAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>eatlog.account.lastauth_at</code>.
     */
    public LocalDateTime getLastauthAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>eatlog.account.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>eatlog.account.name</code>.
     */
    @NotNull
    @Size(max = 32)
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>eatlog.account.site_auth_yandexid</code>.
     */
    public void setSiteAuthYandexid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>eatlog.account.site_auth_yandexid</code>.
     */
    @NotNull
    @Size(max = 30)
    public String getSiteAuthYandexid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>eatlog.account.site_avatar_url</code>.
     */
    public void setSiteAvatarUrl(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>eatlog.account.site_avatar_url</code>.
     */
    @Size(max = 255)
    public String getSiteAvatarUrl() {
        return (String) get(5);
    }

    /**
     * Setter for <code>eatlog.account.locale_segments</code>. Example value:
     * 'ru' or 'en' or 'en_US' or others languages with/without country
     */
    public void setLocaleSegments(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>eatlog.account.locale_segments</code>. Example value:
     * 'ru' or 'en' or 'en_US' or others languages with/without country
     */
    @Size(max = 15)
    public String getLocaleSegments() {
        return (String) get(6);
    }

    /**
     * Setter for <code>eatlog.account.roles</code>.
     */
    public void setRoles(TreeSet<String> value) {
        set(7, value);
    }

    /**
     * Getter for <code>eatlog.account.roles</code>.
     */
    public TreeSet<String> getRoles() {
        return (TreeSet<String>) get(7);
    }

    /**
     * Setter for <code>eatlog.account.ip</code>.
     */
    public void setIp(UInteger value) {
        set(8, value);
    }

    /**
     * Getter for <code>eatlog.account.ip</code>.
     */
    public UInteger getIp() {
        return (UInteger) get(8);
    }

    /**
     * Setter for <code>eatlog.account.is_banned</code>.
     */
    public void setIsBanned(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>eatlog.account.is_banned</code>.
     */
    public Boolean getIsBanned() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>eatlog.account.banned_reason</code>.
     */
    public void setBannedReason(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>eatlog.account.banned_reason</code>.
     */
    @Size(max = 255)
    public String getBannedReason() {
        return (String) get(10);
    }

    /**
     * Setter for <code>eatlog.account.grade_eatlog</code>.
     */
    public void setGradeEatlog(UShort value) {
        set(11, value);
    }

    /**
     * Getter for <code>eatlog.account.grade_eatlog</code>.
     */
    public UShort getGradeEatlog() {
        return (UShort) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountRecord
     */
    public AccountRecord() {
        super(Account.ACCOUNT);
    }

    /**
     * Create a detached, initialised AccountRecord
     */
    public AccountRecord(UInteger id, LocalDateTime createdAt, LocalDateTime lastauthAt, String name, String siteAuthYandexid, String siteAvatarUrl, String localeSegments, TreeSet<String> roles, UInteger ip, Boolean isBanned, String bannedReason, UShort gradeEatlog) {
        super(Account.ACCOUNT);

        setId(id);
        setCreatedAt(createdAt);
        setLastauthAt(lastauthAt);
        setName(name);
        setSiteAuthYandexid(siteAuthYandexid);
        setSiteAvatarUrl(siteAvatarUrl);
        setLocaleSegments(localeSegments);
        setRoles(roles);
        setIp(ip);
        setIsBanned(isBanned);
        setBannedReason(bannedReason);
        setGradeEatlog(gradeEatlog);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AccountRecord
     */
    public AccountRecord(com.github.mbto.eatlog.common.model.eatlog.tables.pojos.Account value) {
        super(Account.ACCOUNT);

        if (value != null) {
            setId(value.getId());
            setCreatedAt(value.getCreatedAt());
            setLastauthAt(value.getLastauthAt());
            setName(value.getName());
            setSiteAuthYandexid(value.getSiteAuthYandexid());
            setSiteAvatarUrl(value.getSiteAvatarUrl());
            setLocaleSegments(value.getLocaleSegments());
            setRoles(value.getRoles());
            setIp(value.getIp());
            setIsBanned(value.getIsBanned());
            setBannedReason(value.getBannedReason());
            setGradeEatlog(value.getGradeEatlog());
            resetChangedOnNotNull();
        }
    }
}
