/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.eatlog.common.model.eatlog.tables.records;


import com.github.mbto.eatlog.common.model.eatlog.tables.Limitation;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LimitationRecord extends UpdatableRecordImpl<LimitationRecord> implements Record9<UInteger, UInteger, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>eatlog.limitation.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>eatlog.limitation.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>eatlog.limitation.account_id</code>.
     */
    public void setAccountId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>eatlog.limitation.account_id</code>.
     */
    @NotNull
    public UInteger getAccountId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>eatlog.limitation.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>eatlog.limitation.title</code>.
     */
    @NotNull
    @Size(max = 32)
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>eatlog.limitation.b</code>.
     */
    public void setB(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>eatlog.limitation.b</code>.
     */
    public BigDecimal getB() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>eatlog.limitation.j</code>.
     */
    public void setJ(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>eatlog.limitation.j</code>.
     */
    public BigDecimal getJ() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>eatlog.limitation.u</code>.
     */
    public void setU(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>eatlog.limitation.u</code>.
     */
    public BigDecimal getU() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>eatlog.limitation.b_to_kkal</code>.
     */
    public void setBToKkal(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>eatlog.limitation.b_to_kkal</code>.
     */
    public BigDecimal getBToKkal() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>eatlog.limitation.j_to_kkal</code>.
     */
    public void setJToKkal(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>eatlog.limitation.j_to_kkal</code>.
     */
    public BigDecimal getJToKkal() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>eatlog.limitation.u_to_kkal</code>.
     */
    public void setUToKkal(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>eatlog.limitation.u_to_kkal</code>.
     */
    public BigDecimal getUToKkal() {
        return (BigDecimal) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<UInteger, UInteger, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<UInteger, UInteger, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return Limitation.LIMITATION.ID;
    }

    @Override
    public Field<UInteger> field2() {
        return Limitation.LIMITATION.ACCOUNT_ID;
    }

    @Override
    public Field<String> field3() {
        return Limitation.LIMITATION.TITLE;
    }

    @Override
    public Field<BigDecimal> field4() {
        return Limitation.LIMITATION.B;
    }

    @Override
    public Field<BigDecimal> field5() {
        return Limitation.LIMITATION.J;
    }

    @Override
    public Field<BigDecimal> field6() {
        return Limitation.LIMITATION.U;
    }

    @Override
    public Field<BigDecimal> field7() {
        return Limitation.LIMITATION.B_TO_KKAL;
    }

    @Override
    public Field<BigDecimal> field8() {
        return Limitation.LIMITATION.J_TO_KKAL;
    }

    @Override
    public Field<BigDecimal> field9() {
        return Limitation.LIMITATION.U_TO_KKAL;
    }

    @Override
    public UInteger component1() {
        return getId();
    }

    @Override
    public UInteger component2() {
        return getAccountId();
    }

    @Override
    public String component3() {
        return getTitle();
    }

    @Override
    public BigDecimal component4() {
        return getB();
    }

    @Override
    public BigDecimal component5() {
        return getJ();
    }

    @Override
    public BigDecimal component6() {
        return getU();
    }

    @Override
    public BigDecimal component7() {
        return getBToKkal();
    }

    @Override
    public BigDecimal component8() {
        return getJToKkal();
    }

    @Override
    public BigDecimal component9() {
        return getUToKkal();
    }

    @Override
    public UInteger value1() {
        return getId();
    }

    @Override
    public UInteger value2() {
        return getAccountId();
    }

    @Override
    public String value3() {
        return getTitle();
    }

    @Override
    public BigDecimal value4() {
        return getB();
    }

    @Override
    public BigDecimal value5() {
        return getJ();
    }

    @Override
    public BigDecimal value6() {
        return getU();
    }

    @Override
    public BigDecimal value7() {
        return getBToKkal();
    }

    @Override
    public BigDecimal value8() {
        return getJToKkal();
    }

    @Override
    public BigDecimal value9() {
        return getUToKkal();
    }

    @Override
    public LimitationRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    @Override
    public LimitationRecord value2(UInteger value) {
        setAccountId(value);
        return this;
    }

    @Override
    public LimitationRecord value3(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public LimitationRecord value4(BigDecimal value) {
        setB(value);
        return this;
    }

    @Override
    public LimitationRecord value5(BigDecimal value) {
        setJ(value);
        return this;
    }

    @Override
    public LimitationRecord value6(BigDecimal value) {
        setU(value);
        return this;
    }

    @Override
    public LimitationRecord value7(BigDecimal value) {
        setBToKkal(value);
        return this;
    }

    @Override
    public LimitationRecord value8(BigDecimal value) {
        setJToKkal(value);
        return this;
    }

    @Override
    public LimitationRecord value9(BigDecimal value) {
        setUToKkal(value);
        return this;
    }

    @Override
    public LimitationRecord values(UInteger value1, UInteger value2, String value3, BigDecimal value4, BigDecimal value5, BigDecimal value6, BigDecimal value7, BigDecimal value8, BigDecimal value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LimitationRecord
     */
    public LimitationRecord() {
        super(Limitation.LIMITATION);
    }

    /**
     * Create a detached, initialised LimitationRecord
     */
    public LimitationRecord(UInteger id, UInteger accountId, String title, BigDecimal b, BigDecimal j, BigDecimal u, BigDecimal bToKkal, BigDecimal jToKkal, BigDecimal uToKkal) {
        super(Limitation.LIMITATION);

        setId(id);
        setAccountId(accountId);
        setTitle(title);
        setB(b);
        setJ(j);
        setU(u);
        setBToKkal(bToKkal);
        setJToKkal(jToKkal);
        setUToKkal(uToKkal);
    }

    /**
     * Create a detached, initialised LimitationRecord
     */
    public LimitationRecord(com.github.mbto.eatlog.common.model.eatlog.tables.pojos.Limitation value) {
        super(Limitation.LIMITATION);

        if (value != null) {
            setId(value.getId());
            setAccountId(value.getAccountId());
            setTitle(value.getTitle());
            setB(value.getB());
            setJ(value.getJ());
            setU(value.getU());
            setBToKkal(value.getBToKkal());
            setJToKkal(value.getJToKkal());
            setUToKkal(value.getUToKkal());
        }
    }
}
