/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.eatlog.common.model.eatlog.tables.records;


import com.github.mbto.eatlog.common.model.eatlog.tables.Limitation;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LimitationRecord extends UpdatableRecordImpl<LimitationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>eatlog.limitation.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>eatlog.limitation.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>eatlog.limitation.account_id</code>.
     */
    public void setAccountId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>eatlog.limitation.account_id</code>.
     */
    @NotNull
    public UInteger getAccountId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>eatlog.limitation.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>eatlog.limitation.title</code>.
     */
    @NotNull
    @Size(max = 32)
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>eatlog.limitation.b</code>.
     */
    public void setB(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>eatlog.limitation.b</code>.
     */
    public BigDecimal getB() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>eatlog.limitation.j</code>.
     */
    public void setJ(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>eatlog.limitation.j</code>.
     */
    public BigDecimal getJ() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>eatlog.limitation.u</code>.
     */
    public void setU(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>eatlog.limitation.u</code>.
     */
    public BigDecimal getU() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>eatlog.limitation.b_to_kkal</code>.
     */
    public void setBToKkal(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>eatlog.limitation.b_to_kkal</code>.
     */
    public BigDecimal getBToKkal() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>eatlog.limitation.j_to_kkal</code>.
     */
    public void setJToKkal(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>eatlog.limitation.j_to_kkal</code>.
     */
    public BigDecimal getJToKkal() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>eatlog.limitation.u_to_kkal</code>.
     */
    public void setUToKkal(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>eatlog.limitation.u_to_kkal</code>.
     */
    public BigDecimal getUToKkal() {
        return (BigDecimal) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LimitationRecord
     */
    public LimitationRecord() {
        super(Limitation.LIMITATION);
    }

    /**
     * Create a detached, initialised LimitationRecord
     */
    public LimitationRecord(UInteger id, UInteger accountId, String title, BigDecimal b, BigDecimal j, BigDecimal u, BigDecimal bToKkal, BigDecimal jToKkal, BigDecimal uToKkal) {
        super(Limitation.LIMITATION);

        setId(id);
        setAccountId(accountId);
        setTitle(title);
        setB(b);
        setJ(j);
        setU(u);
        setBToKkal(bToKkal);
        setJToKkal(jToKkal);
        setUToKkal(uToKkal);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised LimitationRecord
     */
    public LimitationRecord(com.github.mbto.eatlog.common.model.eatlog.tables.pojos.Limitation value) {
        super(Limitation.LIMITATION);

        if (value != null) {
            setId(value.getId());
            setAccountId(value.getAccountId());
            setTitle(value.getTitle());
            setB(value.getB());
            setJ(value.getJ());
            setU(value.getU());
            setBToKkal(value.getBToKkal());
            setJToKkal(value.getJToKkal());
            setUToKkal(value.getUToKkal());
            resetChangedOnNotNull();
        }
    }
}
