/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.eatlog.common.model.eatlog.tables.records;


import com.github.mbto.eatlog.common.model.eatlog.tables.Product;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * bju and kkal values: per 100 gram
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProductRecord extends UpdatableRecordImpl<ProductRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>eatlog.product.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>eatlog.product.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>eatlog.product.store_id</code>.
     */
    public void setStoreId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>eatlog.product.store_id</code>.
     */
    @NotNull
    public UInteger getStoreId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>eatlog.product.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>eatlog.product.title</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>eatlog.product.portion_gram</code>.
     */
    public void setPortionGram(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>eatlog.product.portion_gram</code>.
     */
    @NotNull
    public Short getPortionGram() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>eatlog.product.b</code>.
     */
    public void setB(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>eatlog.product.b</code>.
     */
    @NotNull
    public BigDecimal getB() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>eatlog.product.j</code>.
     */
    public void setJ(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>eatlog.product.j</code>.
     */
    @NotNull
    public BigDecimal getJ() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>eatlog.product.u</code>.
     */
    public void setU(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>eatlog.product.u</code>.
     */
    @NotNull
    public BigDecimal getU() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>eatlog.product.b_to_kkal</code>.
     */
    public void setBToKkal(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>eatlog.product.b_to_kkal</code>.
     */
    @NotNull
    public BigDecimal getBToKkal() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>eatlog.product.j_to_kkal</code>.
     */
    public void setJToKkal(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>eatlog.product.j_to_kkal</code>.
     */
    @NotNull
    public BigDecimal getJToKkal() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>eatlog.product.u_to_kkal</code>.
     */
    public void setUToKkal(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>eatlog.product.u_to_kkal</code>.
     */
    @NotNull
    public BigDecimal getUToKkal() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>eatlog.product.kkal</code>.
     */
    public void setKkal(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>eatlog.product.kkal</code>.
     */
    @NotNull
    public BigDecimal getKkal() {
        return (BigDecimal) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductRecord
     */
    public ProductRecord() {
        super(Product.PRODUCT);
    }

    /**
     * Create a detached, initialised ProductRecord
     */
    public ProductRecord(UInteger id, UInteger storeId, String title, Short portionGram, BigDecimal b, BigDecimal j, BigDecimal u, BigDecimal bToKkal, BigDecimal jToKkal, BigDecimal uToKkal, BigDecimal kkal) {
        super(Product.PRODUCT);

        setId(id);
        setStoreId(storeId);
        setTitle(title);
        setPortionGram(portionGram);
        setB(b);
        setJ(j);
        setU(u);
        setBToKkal(bToKkal);
        setJToKkal(jToKkal);
        setUToKkal(uToKkal);
        setKkal(kkal);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ProductRecord
     */
    public ProductRecord(com.github.mbto.eatlog.common.model.eatlog.tables.pojos.Product value) {
        super(Product.PRODUCT);

        if (value != null) {
            setId(value.getId());
            setStoreId(value.getStoreId());
            setTitle(value.getTitle());
            setPortionGram(value.getPortionGram());
            setB(value.getB());
            setJ(value.getJ());
            setU(value.getU());
            setBToKkal(value.getBToKkal());
            setJToKkal(value.getJToKkal());
            setUToKkal(value.getUToKkal());
            setKkal(value.getKkal());
            resetChangedOnNotNull();
        }
    }
}
