/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.eatlog.common.model.eatlog.tables.records;


import com.github.mbto.eatlog.common.model.eatlog.tables.Product;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * bju and kkal values: per 100 gram
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductRecord extends UpdatableRecordImpl<ProductRecord> implements Record11<UInteger, UInteger, String, Short, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>eatlog.product.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>eatlog.product.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>eatlog.product.store_id</code>.
     */
    public void setStoreId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>eatlog.product.store_id</code>.
     */
    @NotNull
    public UInteger getStoreId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>eatlog.product.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>eatlog.product.title</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>eatlog.product.portion_gram</code>.
     */
    public void setPortionGram(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>eatlog.product.portion_gram</code>.
     */
    @NotNull
    public Short getPortionGram() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>eatlog.product.b</code>.
     */
    public void setB(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>eatlog.product.b</code>.
     */
    @NotNull
    public BigDecimal getB() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>eatlog.product.j</code>.
     */
    public void setJ(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>eatlog.product.j</code>.
     */
    @NotNull
    public BigDecimal getJ() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>eatlog.product.u</code>.
     */
    public void setU(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>eatlog.product.u</code>.
     */
    @NotNull
    public BigDecimal getU() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>eatlog.product.b_to_kkal</code>.
     */
    public void setBToKkal(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>eatlog.product.b_to_kkal</code>.
     */
    @NotNull
    public BigDecimal getBToKkal() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>eatlog.product.j_to_kkal</code>.
     */
    public void setJToKkal(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>eatlog.product.j_to_kkal</code>.
     */
    @NotNull
    public BigDecimal getJToKkal() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>eatlog.product.u_to_kkal</code>.
     */
    public void setUToKkal(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>eatlog.product.u_to_kkal</code>.
     */
    @NotNull
    public BigDecimal getUToKkal() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>eatlog.product.kkal</code>.
     */
    public void setKkal(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>eatlog.product.kkal</code>.
     */
    @NotNull
    public BigDecimal getKkal() {
        return (BigDecimal) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<UInteger, UInteger, String, Short, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<UInteger, UInteger, String, Short, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return Product.PRODUCT.ID;
    }

    @Override
    public Field<UInteger> field2() {
        return Product.PRODUCT.STORE_ID;
    }

    @Override
    public Field<String> field3() {
        return Product.PRODUCT.TITLE;
    }

    @Override
    public Field<Short> field4() {
        return Product.PRODUCT.PORTION_GRAM;
    }

    @Override
    public Field<BigDecimal> field5() {
        return Product.PRODUCT.B;
    }

    @Override
    public Field<BigDecimal> field6() {
        return Product.PRODUCT.J;
    }

    @Override
    public Field<BigDecimal> field7() {
        return Product.PRODUCT.U;
    }

    @Override
    public Field<BigDecimal> field8() {
        return Product.PRODUCT.B_TO_KKAL;
    }

    @Override
    public Field<BigDecimal> field9() {
        return Product.PRODUCT.J_TO_KKAL;
    }

    @Override
    public Field<BigDecimal> field10() {
        return Product.PRODUCT.U_TO_KKAL;
    }

    @Override
    public Field<BigDecimal> field11() {
        return Product.PRODUCT.KKAL;
    }

    @Override
    public UInteger component1() {
        return getId();
    }

    @Override
    public UInteger component2() {
        return getStoreId();
    }

    @Override
    public String component3() {
        return getTitle();
    }

    @Override
    public Short component4() {
        return getPortionGram();
    }

    @Override
    public BigDecimal component5() {
        return getB();
    }

    @Override
    public BigDecimal component6() {
        return getJ();
    }

    @Override
    public BigDecimal component7() {
        return getU();
    }

    @Override
    public BigDecimal component8() {
        return getBToKkal();
    }

    @Override
    public BigDecimal component9() {
        return getJToKkal();
    }

    @Override
    public BigDecimal component10() {
        return getUToKkal();
    }

    @Override
    public BigDecimal component11() {
        return getKkal();
    }

    @Override
    public UInteger value1() {
        return getId();
    }

    @Override
    public UInteger value2() {
        return getStoreId();
    }

    @Override
    public String value3() {
        return getTitle();
    }

    @Override
    public Short value4() {
        return getPortionGram();
    }

    @Override
    public BigDecimal value5() {
        return getB();
    }

    @Override
    public BigDecimal value6() {
        return getJ();
    }

    @Override
    public BigDecimal value7() {
        return getU();
    }

    @Override
    public BigDecimal value8() {
        return getBToKkal();
    }

    @Override
    public BigDecimal value9() {
        return getJToKkal();
    }

    @Override
    public BigDecimal value10() {
        return getUToKkal();
    }

    @Override
    public BigDecimal value11() {
        return getKkal();
    }

    @Override
    public ProductRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    @Override
    public ProductRecord value2(UInteger value) {
        setStoreId(value);
        return this;
    }

    @Override
    public ProductRecord value3(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public ProductRecord value4(Short value) {
        setPortionGram(value);
        return this;
    }

    @Override
    public ProductRecord value5(BigDecimal value) {
        setB(value);
        return this;
    }

    @Override
    public ProductRecord value6(BigDecimal value) {
        setJ(value);
        return this;
    }

    @Override
    public ProductRecord value7(BigDecimal value) {
        setU(value);
        return this;
    }

    @Override
    public ProductRecord value8(BigDecimal value) {
        setBToKkal(value);
        return this;
    }

    @Override
    public ProductRecord value9(BigDecimal value) {
        setJToKkal(value);
        return this;
    }

    @Override
    public ProductRecord value10(BigDecimal value) {
        setUToKkal(value);
        return this;
    }

    @Override
    public ProductRecord value11(BigDecimal value) {
        setKkal(value);
        return this;
    }

    @Override
    public ProductRecord values(UInteger value1, UInteger value2, String value3, Short value4, BigDecimal value5, BigDecimal value6, BigDecimal value7, BigDecimal value8, BigDecimal value9, BigDecimal value10, BigDecimal value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductRecord
     */
    public ProductRecord() {
        super(Product.PRODUCT);
    }

    /**
     * Create a detached, initialised ProductRecord
     */
    public ProductRecord(UInteger id, UInteger storeId, String title, Short portionGram, BigDecimal b, BigDecimal j, BigDecimal u, BigDecimal bToKkal, BigDecimal jToKkal, BigDecimal uToKkal, BigDecimal kkal) {
        super(Product.PRODUCT);

        setId(id);
        setStoreId(storeId);
        setTitle(title);
        setPortionGram(portionGram);
        setB(b);
        setJ(j);
        setU(u);
        setBToKkal(bToKkal);
        setJToKkal(jToKkal);
        setUToKkal(uToKkal);
        setKkal(kkal);
    }

    /**
     * Create a detached, initialised ProductRecord
     */
    public ProductRecord(com.github.mbto.eatlog.common.model.eatlog.tables.pojos.Product value) {
        super(Product.PRODUCT);

        if (value != null) {
            setId(value.getId());
            setStoreId(value.getStoreId());
            setTitle(value.getTitle());
            setPortionGram(value.getPortionGram());
            setB(value.getB());
            setJ(value.getJ());
            setU(value.getU());
            setBToKkal(value.getBToKkal());
            setJToKkal(value.getJToKkal());
            setUToKkal(value.getUToKkal());
            setKkal(value.getKkal());
        }
    }
}
