/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.eatlog.common.model.eatlog.tables.records;


import com.github.mbto.eatlog.common.model.eatlog.tables.Setting;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.util.TreeSet;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SettingRecord extends UpdatableRecordImpl<SettingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>eatlog.setting.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>eatlog.setting.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>eatlog.setting.key</code>.
     */
    public void setKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>eatlog.setting.key</code>.
     */
    @NotNull
    @Size(max = 32)
    public String getKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>eatlog.setting.value</code>. string or json
     */
    public void setValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>eatlog.setting.value</code>. string or json
     */
    public String getValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>eatlog.setting.roles</code>. json array with roles
     * names, example: ["owner","admin"]
     */
    public void setRoles(TreeSet<String> value) {
        set(3, value);
    }

    /**
     * Getter for <code>eatlog.setting.roles</code>. json array with roles
     * names, example: ["owner","admin"]
     */
    public TreeSet<String> getRoles() {
        return (TreeSet<String>) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SettingRecord
     */
    public SettingRecord() {
        super(Setting.SETTING);
    }

    /**
     * Create a detached, initialised SettingRecord
     */
    public SettingRecord(UInteger id, String key, String value, TreeSet<String> roles) {
        super(Setting.SETTING);

        setId(id);
        setKey(key);
        setValue(value);
        setRoles(roles);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised SettingRecord
     */
    public SettingRecord(com.github.mbto.eatlog.common.model.eatlog.tables.pojos.Setting value) {
        super(Setting.SETTING);

        if (value != null) {
            setId(value.getId());
            setKey(value.getKey());
            setValue(value.getValue());
            setRoles(value.getRoles());
            resetChangedOnNotNull();
        }
    }
}
