/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.eatlog.common.model.eatlog.tables.records;


import com.github.mbto.eatlog.common.model.eatlog.tables.Store;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StoreRecord extends UpdatableRecordImpl<StoreRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>eatlog.store.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>eatlog.store.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>eatlog.store.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>eatlog.store.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>eatlog.store.account_id</code>.
     */
    public void setAccountId(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>eatlog.store.account_id</code>.
     */
    @NotNull
    public UInteger getAccountId() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>eatlog.store.title</code>.
     */
    public void setTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>eatlog.store.title</code>.
     */
    @NotNull
    @Size(max = 32)
    public String getTitle() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StoreRecord
     */
    public StoreRecord() {
        super(Store.STORE);
    }

    /**
     * Create a detached, initialised StoreRecord
     */
    public StoreRecord(UInteger id, LocalDateTime updatedAt, UInteger accountId, String title) {
        super(Store.STORE);

        setId(id);
        setUpdatedAt(updatedAt);
        setAccountId(accountId);
        setTitle(title);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised StoreRecord
     */
    public StoreRecord(com.github.mbto.eatlog.common.model.eatlog.tables.pojos.Store value) {
        super(Store.STORE);

        if (value != null) {
            setId(value.getId());
            setUpdatedAt(value.getUpdatedAt());
            setAccountId(value.getAccountId());
            setTitle(value.getTitle());
            resetChangedOnNotNull();
        }
    }
}
