/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.eatlog.common.model.eatlog.tables.records;


import com.github.mbto.eatlog.common.model.eatlog.tables.Weight;

import jakarta.validation.constraints.NotNull;

import java.math.BigDecimal;
import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WeightRecord extends UpdatableRecordImpl<WeightRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>eatlog.weight.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>eatlog.weight.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>eatlog.weight.date</code>.
     */
    public void setDate(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>eatlog.weight.date</code>.
     */
    @NotNull
    public LocalDate getDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>eatlog.weight.account_id</code>.
     */
    public void setAccountId(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>eatlog.weight.account_id</code>.
     */
    @NotNull
    public UInteger getAccountId() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>eatlog.weight.kilogram</code>.
     */
    public void setKilogram(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>eatlog.weight.kilogram</code>.
     */
    @NotNull
    public BigDecimal getKilogram() {
        return (BigDecimal) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WeightRecord
     */
    public WeightRecord() {
        super(Weight.WEIGHT);
    }

    /**
     * Create a detached, initialised WeightRecord
     */
    public WeightRecord(UInteger id, LocalDate date, UInteger accountId, BigDecimal kilogram) {
        super(Weight.WEIGHT);

        setId(id);
        setDate(date);
        setAccountId(accountId);
        setKilogram(kilogram);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised WeightRecord
     */
    public WeightRecord(com.github.mbto.eatlog.common.model.eatlog.tables.pojos.Weight value) {
        super(Weight.WEIGHT);

        if (value != null) {
            setId(value.getId());
            setDate(value.getDate());
            setAccountId(value.getAccountId());
            setKilogram(value.getKilogram());
            resetChangedOnNotNull();
        }
    }
}
