/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.eatlog.common.model.eatlog.tables.pojos;


import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.math.BigDecimal;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Limitation implements Serializable {

    private static final long serialVersionUID = 1L;

    private UInteger id;
    private UInteger accountId;
    private String title;
    private BigDecimal b;
    private BigDecimal j;
    private BigDecimal u;
    private BigDecimal bToKkal;
    private BigDecimal jToKkal;
    private BigDecimal uToKkal;

    public Limitation() {}

    public Limitation(Limitation value) {
        this.id = value.id;
        this.accountId = value.accountId;
        this.title = value.title;
        this.b = value.b;
        this.j = value.j;
        this.u = value.u;
        this.bToKkal = value.bToKkal;
        this.jToKkal = value.jToKkal;
        this.uToKkal = value.uToKkal;
    }

    public Limitation(
        UInteger id,
        UInteger accountId,
        String title,
        BigDecimal b,
        BigDecimal j,
        BigDecimal u,
        BigDecimal bToKkal,
        BigDecimal jToKkal,
        BigDecimal uToKkal
    ) {
        this.id = id;
        this.accountId = accountId;
        this.title = title;
        this.b = b;
        this.j = j;
        this.u = u;
        this.bToKkal = bToKkal;
        this.jToKkal = jToKkal;
        this.uToKkal = uToKkal;
    }

    /**
     * Getter for <code>eatlog.limitation.id</code>.
     */
    public UInteger getId() {
        return this.id;
    }

    /**
     * Setter for <code>eatlog.limitation.id</code>.
     */
    public void setId(UInteger id) {
        this.id = id;
    }

    /**
     * Getter for <code>eatlog.limitation.account_id</code>.
     */
    @NotNull
    public UInteger getAccountId() {
        return this.accountId;
    }

    /**
     * Setter for <code>eatlog.limitation.account_id</code>.
     */
    public void setAccountId(UInteger accountId) {
        this.accountId = accountId;
    }

    /**
     * Getter for <code>eatlog.limitation.title</code>.
     */
    @NotNull
    @Size(max = 32)
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>eatlog.limitation.title</code>.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>eatlog.limitation.b</code>.
     */
    public BigDecimal getB() {
        return this.b;
    }

    /**
     * Setter for <code>eatlog.limitation.b</code>.
     */
    public void setB(BigDecimal b) {
        this.b = b;
    }

    /**
     * Getter for <code>eatlog.limitation.j</code>.
     */
    public BigDecimal getJ() {
        return this.j;
    }

    /**
     * Setter for <code>eatlog.limitation.j</code>.
     */
    public void setJ(BigDecimal j) {
        this.j = j;
    }

    /**
     * Getter for <code>eatlog.limitation.u</code>.
     */
    public BigDecimal getU() {
        return this.u;
    }

    /**
     * Setter for <code>eatlog.limitation.u</code>.
     */
    public void setU(BigDecimal u) {
        this.u = u;
    }

    /**
     * Getter for <code>eatlog.limitation.b_to_kkal</code>.
     */
    public BigDecimal getBToKkal() {
        return this.bToKkal;
    }

    /**
     * Setter for <code>eatlog.limitation.b_to_kkal</code>.
     */
    public void setBToKkal(BigDecimal bToKkal) {
        this.bToKkal = bToKkal;
    }

    /**
     * Getter for <code>eatlog.limitation.j_to_kkal</code>.
     */
    public BigDecimal getJToKkal() {
        return this.jToKkal;
    }

    /**
     * Setter for <code>eatlog.limitation.j_to_kkal</code>.
     */
    public void setJToKkal(BigDecimal jToKkal) {
        this.jToKkal = jToKkal;
    }

    /**
     * Getter for <code>eatlog.limitation.u_to_kkal</code>.
     */
    public BigDecimal getUToKkal() {
        return this.uToKkal;
    }

    /**
     * Setter for <code>eatlog.limitation.u_to_kkal</code>.
     */
    public void setUToKkal(BigDecimal uToKkal) {
        this.uToKkal = uToKkal;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Limitation other = (Limitation) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.accountId == null) {
            if (other.accountId != null)
                return false;
        }
        else if (!this.accountId.equals(other.accountId))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.b == null) {
            if (other.b != null)
                return false;
        }
        else if (!this.b.equals(other.b))
            return false;
        if (this.j == null) {
            if (other.j != null)
                return false;
        }
        else if (!this.j.equals(other.j))
            return false;
        if (this.u == null) {
            if (other.u != null)
                return false;
        }
        else if (!this.u.equals(other.u))
            return false;
        if (this.bToKkal == null) {
            if (other.bToKkal != null)
                return false;
        }
        else if (!this.bToKkal.equals(other.bToKkal))
            return false;
        if (this.jToKkal == null) {
            if (other.jToKkal != null)
                return false;
        }
        else if (!this.jToKkal.equals(other.jToKkal))
            return false;
        if (this.uToKkal == null) {
            if (other.uToKkal != null)
                return false;
        }
        else if (!this.uToKkal.equals(other.uToKkal))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.accountId == null) ? 0 : this.accountId.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.b == null) ? 0 : this.b.hashCode());
        result = prime * result + ((this.j == null) ? 0 : this.j.hashCode());
        result = prime * result + ((this.u == null) ? 0 : this.u.hashCode());
        result = prime * result + ((this.bToKkal == null) ? 0 : this.bToKkal.hashCode());
        result = prime * result + ((this.jToKkal == null) ? 0 : this.jToKkal.hashCode());
        result = prime * result + ((this.uToKkal == null) ? 0 : this.uToKkal.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Limitation (");

        sb.append(id);
        sb.append(", ").append(accountId);
        sb.append(", ").append(title);
        sb.append(", ").append(b);
        sb.append(", ").append(j);
        sb.append(", ").append(u);
        sb.append(", ").append(bToKkal);
        sb.append(", ").append(jToKkal);
        sb.append(", ").append(uToKkal);

        sb.append(")");
        return sb.toString();
    }
}
