/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.eatlog.common.model.eatlog.tables.pojos;


import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.math.BigDecimal;

import org.jooq.types.UInteger;


/**
 * bju and kkal values: per 100 gram
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Product implements Serializable {

    private static final long serialVersionUID = 1L;

    private UInteger id;
    private UInteger storeId;
    private String title;
    private Short portionGram;
    private BigDecimal b;
    private BigDecimal j;
    private BigDecimal u;
    private BigDecimal bToKkal;
    private BigDecimal jToKkal;
    private BigDecimal uToKkal;
    private BigDecimal kkal;

    public Product() {}

    public Product(Product value) {
        this.id = value.id;
        this.storeId = value.storeId;
        this.title = value.title;
        this.portionGram = value.portionGram;
        this.b = value.b;
        this.j = value.j;
        this.u = value.u;
        this.bToKkal = value.bToKkal;
        this.jToKkal = value.jToKkal;
        this.uToKkal = value.uToKkal;
        this.kkal = value.kkal;
    }

    public Product(
        UInteger id,
        UInteger storeId,
        String title,
        Short portionGram,
        BigDecimal b,
        BigDecimal j,
        BigDecimal u,
        BigDecimal bToKkal,
        BigDecimal jToKkal,
        BigDecimal uToKkal,
        BigDecimal kkal
    ) {
        this.id = id;
        this.storeId = storeId;
        this.title = title;
        this.portionGram = portionGram;
        this.b = b;
        this.j = j;
        this.u = u;
        this.bToKkal = bToKkal;
        this.jToKkal = jToKkal;
        this.uToKkal = uToKkal;
        this.kkal = kkal;
    }

    /**
     * Getter for <code>eatlog.product.id</code>.
     */
    public UInteger getId() {
        return this.id;
    }

    /**
     * Setter for <code>eatlog.product.id</code>.
     */
    public void setId(UInteger id) {
        this.id = id;
    }

    /**
     * Getter for <code>eatlog.product.store_id</code>.
     */
    @NotNull
    public UInteger getStoreId() {
        return this.storeId;
    }

    /**
     * Setter for <code>eatlog.product.store_id</code>.
     */
    public void setStoreId(UInteger storeId) {
        this.storeId = storeId;
    }

    /**
     * Getter for <code>eatlog.product.title</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>eatlog.product.title</code>.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>eatlog.product.portion_gram</code>.
     */
    @NotNull
    public Short getPortionGram() {
        return this.portionGram;
    }

    /**
     * Setter for <code>eatlog.product.portion_gram</code>.
     */
    public void setPortionGram(Short portionGram) {
        this.portionGram = portionGram;
    }

    /**
     * Getter for <code>eatlog.product.b</code>.
     */
    @NotNull
    public BigDecimal getB() {
        return this.b;
    }

    /**
     * Setter for <code>eatlog.product.b</code>.
     */
    public void setB(BigDecimal b) {
        this.b = b;
    }

    /**
     * Getter for <code>eatlog.product.j</code>.
     */
    @NotNull
    public BigDecimal getJ() {
        return this.j;
    }

    /**
     * Setter for <code>eatlog.product.j</code>.
     */
    public void setJ(BigDecimal j) {
        this.j = j;
    }

    /**
     * Getter for <code>eatlog.product.u</code>.
     */
    @NotNull
    public BigDecimal getU() {
        return this.u;
    }

    /**
     * Setter for <code>eatlog.product.u</code>.
     */
    public void setU(BigDecimal u) {
        this.u = u;
    }

    /**
     * Getter for <code>eatlog.product.b_to_kkal</code>.
     */
    @NotNull
    public BigDecimal getBToKkal() {
        return this.bToKkal;
    }

    /**
     * Setter for <code>eatlog.product.b_to_kkal</code>.
     */
    public void setBToKkal(BigDecimal bToKkal) {
        this.bToKkal = bToKkal;
    }

    /**
     * Getter for <code>eatlog.product.j_to_kkal</code>.
     */
    @NotNull
    public BigDecimal getJToKkal() {
        return this.jToKkal;
    }

    /**
     * Setter for <code>eatlog.product.j_to_kkal</code>.
     */
    public void setJToKkal(BigDecimal jToKkal) {
        this.jToKkal = jToKkal;
    }

    /**
     * Getter for <code>eatlog.product.u_to_kkal</code>.
     */
    @NotNull
    public BigDecimal getUToKkal() {
        return this.uToKkal;
    }

    /**
     * Setter for <code>eatlog.product.u_to_kkal</code>.
     */
    public void setUToKkal(BigDecimal uToKkal) {
        this.uToKkal = uToKkal;
    }

    /**
     * Getter for <code>eatlog.product.kkal</code>.
     */
    @NotNull
    public BigDecimal getKkal() {
        return this.kkal;
    }

    /**
     * Setter for <code>eatlog.product.kkal</code>.
     */
    public void setKkal(BigDecimal kkal) {
        this.kkal = kkal;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Product other = (Product) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.storeId == null) {
            if (other.storeId != null)
                return false;
        }
        else if (!this.storeId.equals(other.storeId))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.portionGram == null) {
            if (other.portionGram != null)
                return false;
        }
        else if (!this.portionGram.equals(other.portionGram))
            return false;
        if (this.b == null) {
            if (other.b != null)
                return false;
        }
        else if (!this.b.equals(other.b))
            return false;
        if (this.j == null) {
            if (other.j != null)
                return false;
        }
        else if (!this.j.equals(other.j))
            return false;
        if (this.u == null) {
            if (other.u != null)
                return false;
        }
        else if (!this.u.equals(other.u))
            return false;
        if (this.bToKkal == null) {
            if (other.bToKkal != null)
                return false;
        }
        else if (!this.bToKkal.equals(other.bToKkal))
            return false;
        if (this.jToKkal == null) {
            if (other.jToKkal != null)
                return false;
        }
        else if (!this.jToKkal.equals(other.jToKkal))
            return false;
        if (this.uToKkal == null) {
            if (other.uToKkal != null)
                return false;
        }
        else if (!this.uToKkal.equals(other.uToKkal))
            return false;
        if (this.kkal == null) {
            if (other.kkal != null)
                return false;
        }
        else if (!this.kkal.equals(other.kkal))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.storeId == null) ? 0 : this.storeId.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.portionGram == null) ? 0 : this.portionGram.hashCode());
        result = prime * result + ((this.b == null) ? 0 : this.b.hashCode());
        result = prime * result + ((this.j == null) ? 0 : this.j.hashCode());
        result = prime * result + ((this.u == null) ? 0 : this.u.hashCode());
        result = prime * result + ((this.bToKkal == null) ? 0 : this.bToKkal.hashCode());
        result = prime * result + ((this.jToKkal == null) ? 0 : this.jToKkal.hashCode());
        result = prime * result + ((this.uToKkal == null) ? 0 : this.uToKkal.hashCode());
        result = prime * result + ((this.kkal == null) ? 0 : this.kkal.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Product (");

        sb.append(id);
        sb.append(", ").append(storeId);
        sb.append(", ").append(title);
        sb.append(", ").append(portionGram);
        sb.append(", ").append(b);
        sb.append(", ").append(j);
        sb.append(", ").append(u);
        sb.append(", ").append(bToKkal);
        sb.append(", ").append(jToKkal);
        sb.append(", ").append(uToKkal);
        sb.append(", ").append(kkal);

        sb.append(")");
        return sb.toString();
    }
}
