/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.eatlog.common.model.eatlog.tables.pojos;


import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.util.TreeSet;

import org.jooq.types.UInteger;


/**
 * Create OAuth 2.0 client id: https://console.cloud.google.com/apis/credentials
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Setting implements Serializable {

    private static final long serialVersionUID = 1L;

    private UInteger id;
    private String key;
    private String value;
    private TreeSet<String> roles;

    public Setting() {}

    public Setting(Setting value) {
        this.id = value.id;
        this.key = value.key;
        this.value = value.value;
        this.roles = value.roles;
    }

    public Setting(
        UInteger id,
        String key,
        String value,
        TreeSet<String> roles
    ) {
        this.id = id;
        this.key = key;
        this.value = value;
        this.roles = roles;
    }

    /**
     * Getter for <code>eatlog.setting.id</code>.
     */
    public UInteger getId() {
        return this.id;
    }

    /**
     * Setter for <code>eatlog.setting.id</code>.
     */
    public void setId(UInteger id) {
        this.id = id;
    }

    /**
     * Getter for <code>eatlog.setting.key</code>.
     */
    @NotNull
    @Size(max = 32)
    public String getKey() {
        return this.key;
    }

    /**
     * Setter for <code>eatlog.setting.key</code>.
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * Getter for <code>eatlog.setting.value</code>. string or json
     */
    public String getValue() {
        return this.value;
    }

    /**
     * Setter for <code>eatlog.setting.value</code>. string or json
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Getter for <code>eatlog.setting.roles</code>. json array with roles
     * names, example: ["owner","admin"]
     */
    public TreeSet<String> getRoles() {
        return this.roles;
    }

    /**
     * Setter for <code>eatlog.setting.roles</code>. json array with roles
     * names, example: ["owner","admin"]
     */
    public void setRoles(TreeSet<String> roles) {
        this.roles = roles;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Setting other = (Setting) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.key == null) {
            if (other.key != null)
                return false;
        }
        else if (!this.key.equals(other.key))
            return false;
        if (this.value == null) {
            if (other.value != null)
                return false;
        }
        else if (!this.value.equals(other.value))
            return false;
        if (this.roles == null) {
            if (other.roles != null)
                return false;
        }
        else if (!this.roles.equals(other.roles))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.key == null) ? 0 : this.key.hashCode());
        result = prime * result + ((this.value == null) ? 0 : this.value.hashCode());
        result = prime * result + ((this.roles == null) ? 0 : this.roles.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Setting (");

        sb.append(id);
        sb.append(", ").append(key);
        sb.append(", ").append(value);
        sb.append(", ").append(roles);

        sb.append(")");
        return sb.toString();
    }
}
