/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.eatlog.common.model.eatlog.tables.pojos;


import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Store implements Serializable {

    private static final long serialVersionUID = 1L;

    private UInteger id;
    private LocalDateTime updatedAt;
    private UInteger accountId;
    private String title;

    public Store() {}

    public Store(Store value) {
        this.id = value.id;
        this.updatedAt = value.updatedAt;
        this.accountId = value.accountId;
        this.title = value.title;
    }

    public Store(
        UInteger id,
        LocalDateTime updatedAt,
        UInteger accountId,
        String title
    ) {
        this.id = id;
        this.updatedAt = updatedAt;
        this.accountId = accountId;
        this.title = title;
    }

    /**
     * Getter for <code>eatlog.store.id</code>.
     */
    public UInteger getId() {
        return this.id;
    }

    /**
     * Setter for <code>eatlog.store.id</code>.
     */
    public void setId(UInteger id) {
        this.id = id;
    }

    /**
     * Getter for <code>eatlog.store.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>eatlog.store.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>eatlog.store.account_id</code>.
     */
    @NotNull
    public UInteger getAccountId() {
        return this.accountId;
    }

    /**
     * Setter for <code>eatlog.store.account_id</code>.
     */
    public void setAccountId(UInteger accountId) {
        this.accountId = accountId;
    }

    /**
     * Getter for <code>eatlog.store.title</code>.
     */
    @NotNull
    @Size(max = 32)
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>eatlog.store.title</code>.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Store other = (Store) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        if (this.accountId == null) {
            if (other.accountId != null)
                return false;
        }
        else if (!this.accountId.equals(other.accountId))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        result = prime * result + ((this.accountId == null) ? 0 : this.accountId.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Store (");

        sb.append(id);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(accountId);
        sb.append(", ").append(title);

        sb.append(")");
        return sb.toString();
    }
}
