/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.eatlog.common.model.eatlog.tables.pojos;


import jakarta.validation.constraints.NotNull;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Weight implements Serializable {

    private static final long serialVersionUID = 1L;

    private UInteger id;
    private LocalDate date;
    private UInteger accountId;
    private BigDecimal kilogram;

    public Weight() {}

    public Weight(Weight value) {
        this.id = value.id;
        this.date = value.date;
        this.accountId = value.accountId;
        this.kilogram = value.kilogram;
    }

    public Weight(
        UInteger id,
        LocalDate date,
        UInteger accountId,
        BigDecimal kilogram
    ) {
        this.id = id;
        this.date = date;
        this.accountId = accountId;
        this.kilogram = kilogram;
    }

    /**
     * Getter for <code>eatlog.weight.id</code>.
     */
    public UInteger getId() {
        return this.id;
    }

    /**
     * Setter for <code>eatlog.weight.id</code>.
     */
    public void setId(UInteger id) {
        this.id = id;
    }

    /**
     * Getter for <code>eatlog.weight.date</code>.
     */
    @NotNull
    public LocalDate getDate() {
        return this.date;
    }

    /**
     * Setter for <code>eatlog.weight.date</code>.
     */
    public void setDate(LocalDate date) {
        this.date = date;
    }

    /**
     * Getter for <code>eatlog.weight.account_id</code>.
     */
    @NotNull
    public UInteger getAccountId() {
        return this.accountId;
    }

    /**
     * Setter for <code>eatlog.weight.account_id</code>.
     */
    public void setAccountId(UInteger accountId) {
        this.accountId = accountId;
    }

    /**
     * Getter for <code>eatlog.weight.kilogram</code>.
     */
    @NotNull
    public BigDecimal getKilogram() {
        return this.kilogram;
    }

    /**
     * Setter for <code>eatlog.weight.kilogram</code>.
     */
    public void setKilogram(BigDecimal kilogram) {
        this.kilogram = kilogram;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Weight other = (Weight) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.date == null) {
            if (other.date != null)
                return false;
        }
        else if (!this.date.equals(other.date))
            return false;
        if (this.accountId == null) {
            if (other.accountId != null)
                return false;
        }
        else if (!this.accountId.equals(other.accountId))
            return false;
        if (this.kilogram == null) {
            if (other.kilogram != null)
                return false;
        }
        else if (!this.kilogram.equals(other.kilogram))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.date == null) ? 0 : this.date.hashCode());
        result = prime * result + ((this.accountId == null) ? 0 : this.accountId.hashCode());
        result = prime * result + ((this.kilogram == null) ? 0 : this.kilogram.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Weight (");

        sb.append(id);
        sb.append(", ").append(date);
        sb.append(", ").append(accountId);
        sb.append(", ").append(kilogram);

        sb.append(")");
        return sb.toString();
    }
}
