/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.eatlog.common.model.eatlog;


import com.github.mbto.eatlog.common.model.eatlog.tables.Account;
import com.github.mbto.eatlog.common.model.eatlog.tables.Consumed;
import com.github.mbto.eatlog.common.model.eatlog.tables.Limitation;
import com.github.mbto.eatlog.common.model.eatlog.tables.Product;
import com.github.mbto.eatlog.common.model.eatlog.tables.Setting;
import com.github.mbto.eatlog.common.model.eatlog.tables.Store;
import com.github.mbto.eatlog.common.model.eatlog.tables.Weight;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Eatlog extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>eatlog</code>
     */
    public static final Eatlog EATLOG = new Eatlog();

    /**
     * The table <code>eatlog.account</code>.
     */
    public final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>eatlog.consumed</code>.
     */
    public final Consumed CONSUMED = Consumed.CONSUMED;

    /**
     * The table <code>eatlog.limitation</code>.
     */
    public final Limitation LIMITATION = Limitation.LIMITATION;

    /**
     * bju and kkal values: per 100 gram
     */
    public final Product PRODUCT = Product.PRODUCT;

    /**
     * The table <code>eatlog.setting</code>.
     */
    public final Setting SETTING = Setting.SETTING;

    /**
     * The table <code>eatlog.store</code>.
     */
    public final Store STORE = Store.STORE;

    /**
     * The table <code>eatlog.weight</code>.
     */
    public final Weight WEIGHT = Weight.WEIGHT;

    /**
     * No further instances allowed
     */
    private Eatlog() {
        super("eatlog", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Account.ACCOUNT,
            Consumed.CONSUMED,
            Limitation.LIMITATION,
            Product.PRODUCT,
            Setting.SETTING,
            Store.STORE,
            Weight.WEIGHT
        );
    }
}
