/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.eatlog.common.model.eatlog;


import com.github.mbto.eatlog.common.model.eatlog.routines.FindGeonameIdByIp;

import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.types.UInteger;


/**
 * Convenience access to all stored procedures and functions in eatlog.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Routines {

    /**
     * Call <code>eatlog.find_geoname_id_by_ip</code>
     */
    public static UInteger findGeonameIdByIp(
          Configuration configuration
        , String ip
    ) {
        FindGeonameIdByIp f = new FindGeonameIdByIp();
        f.setIp(ip);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>eatlog.find_geoname_id_by_ip</code> as a field.
     */
    public static Field<UInteger> findGeonameIdByIp(
          String ip
    ) {
        FindGeonameIdByIp f = new FindGeonameIdByIp();
        f.setIp(ip);

        return f.asField();
    }

    /**
     * Get <code>eatlog.find_geoname_id_by_ip</code> as a field.
     */
    public static Field<UInteger> findGeonameIdByIp(
          Field<String> ip
    ) {
        FindGeonameIdByIp f = new FindGeonameIdByIp();
        f.setIp(ip);

        return f.asField();
    }
}
