/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.eatlog.common.model.eatlog;


import com.github.mbto.eatlog.common.model.eatlog.tables.Account;
import com.github.mbto.eatlog.common.model.eatlog.tables.Consumed;
import com.github.mbto.eatlog.common.model.eatlog.tables.Limitation;
import com.github.mbto.eatlog.common.model.eatlog.tables.Product;
import com.github.mbto.eatlog.common.model.eatlog.tables.Setting;
import com.github.mbto.eatlog.common.model.eatlog.tables.Store;
import com.github.mbto.eatlog.common.model.eatlog.tables.Weight;


/**
 * Convenience access to all tables in eatlog.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>eatlog.account</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>eatlog.consumed</code>.
     */
    public static final Consumed CONSUMED = Consumed.CONSUMED;

    /**
     * The table <code>eatlog.limitation</code>.
     */
    public static final Limitation LIMITATION = Limitation.LIMITATION;

    /**
     * bju and kkal values: per 100 gram
     */
    public static final Product PRODUCT = Product.PRODUCT;

    /**
     * The table <code>eatlog.setting</code>.
     */
    public static final Setting SETTING = Setting.SETTING;

    /**
     * The table <code>eatlog.store</code>.
     */
    public static final Store STORE = Store.STORE;

    /**
     * The table <code>eatlog.weight</code>.
     */
    public static final Weight WEIGHT = Weight.WEIGHT;
}
