/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.eatlog.common.model.eatlog.tables;


import com.github.mbto.eatlog.common.model.eatlog.Eatlog;
import com.github.mbto.eatlog.common.model.eatlog.Indexes;
import com.github.mbto.eatlog.common.model.eatlog.Keys;
import com.github.mbto.eatlog.common.model.eatlog.tables.Limitation.LimitationPath;
import com.github.mbto.eatlog.common.model.eatlog.tables.Store.StorePath;
import com.github.mbto.eatlog.common.model.eatlog.tables.Weight.WeightPath;
import com.github.mbto.eatlog.common.model.eatlog.tables.records.AccountRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.TreeSet;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.jackson.extensions.converters.JSONtoJacksonConverter;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Account extends TableImpl<AccountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>eatlog.account</code>
     */
    public static final Account ACCOUNT = new Account();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccountRecord> getRecordType() {
        return AccountRecord.class;
    }

    /**
     * The column <code>eatlog.account.id</code>.
     */
    public final TableField<AccountRecord, UInteger> ID = createField(DSL.name("id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>eatlog.account.created_at</code>.
     */
    public final TableField<AccountRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>eatlog.account.lastauth_at</code>.
     */
    public final TableField<AccountRecord, LocalDateTime> LASTAUTH_AT = createField(DSL.name("lastauth_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>eatlog.account.name</code>.
     */
    public final TableField<AccountRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>eatlog.account.site_auth_yandexid</code>.
     */
    public final TableField<AccountRecord, String> SITE_AUTH_YANDEXID = createField(DSL.name("site_auth_yandexid"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>eatlog.account.site_avatar_url</code>.
     */
    public final TableField<AccountRecord, String> SITE_AVATAR_URL = createField(DSL.name("site_avatar_url"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>eatlog.account.locale_segments</code>. Example value:
     * 'ru' or 'en' or 'en_US' or others languages with/without country
     */
    public final TableField<AccountRecord, String> LOCALE_SEGMENTS = createField(DSL.name("locale_segments"), SQLDataType.VARCHAR(15).nullable(false).defaultValue(DSL.inline("ru", SQLDataType.VARCHAR)), this, "Example value: 'ru' or 'en' or 'en_US' or others languages with/without country");

    /**
     * The column <code>eatlog.account.roles</code>.
     */
    public final TableField<AccountRecord, TreeSet<String>> ROLES = createField(DSL.name("roles"), SQLDataType.JSON, this, "", new JSONtoJacksonConverter<TreeSet<String>>((Class<TreeSet<String>>) (Class) TreeSet.class));

    /**
     * The column <code>eatlog.account.ip</code>.
     */
    public final TableField<AccountRecord, UInteger> IP = createField(DSL.name("ip"), SQLDataType.INTEGERUNSIGNED, this, "");

    /**
     * The column <code>eatlog.account.is_banned</code>.
     */
    public final TableField<AccountRecord, Boolean> IS_BANNED = createField(DSL.name("is_banned"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>eatlog.account.banned_reason</code>.
     */
    public final TableField<AccountRecord, String> BANNED_REASON = createField(DSL.name("banned_reason"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>eatlog.account.grade_eatlog</code>.
     */
    public final TableField<AccountRecord, UShort> GRADE_EATLOG = createField(DSL.name("grade_eatlog"), SQLDataType.SMALLINTUNSIGNED, this, "");

    private Account(Name alias, Table<AccountRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Account(Name alias, Table<AccountRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>eatlog.account</code> table reference
     */
    public Account(String alias) {
        this(DSL.name(alias), ACCOUNT);
    }

    /**
     * Create an aliased <code>eatlog.account</code> table reference
     */
    public Account(Name alias) {
        this(alias, ACCOUNT);
    }

    /**
     * Create a <code>eatlog.account</code> table reference
     */
    public Account() {
        this(DSL.name("account"), null);
    }

    public <O extends Record> Account(Table<O> path, ForeignKey<O, AccountRecord> childPath, InverseForeignKey<O, AccountRecord> parentPath) {
        super(path, childPath, parentPath, ACCOUNT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AccountPath extends Account implements Path<AccountRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AccountPath(Table<O> path, ForeignKey<O, AccountRecord> childPath, InverseForeignKey<O, AccountRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AccountPath(Name alias, Table<AccountRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AccountPath as(String alias) {
            return new AccountPath(DSL.name(alias), this);
        }

        @Override
        public AccountPath as(Name alias) {
            return new AccountPath(alias, this);
        }

        @Override
        public AccountPath as(Table<?> alias) {
            return new AccountPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Eatlog.EATLOG;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ACCOUNT_CREATED_AT, Indexes.ACCOUNT_GEONAME_ID, Indexes.ACCOUNT_LASTAUTH_AT);
    }

    @Override
    public Identity<AccountRecord, UInteger> getIdentity() {
        return (Identity<AccountRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<AccountRecord> getPrimaryKey() {
        return Keys.KEY_ACCOUNT_PRIMARY;
    }

    @Override
    public List<UniqueKey<AccountRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_ACCOUNT_GOOGLE_SUB);
    }

    private transient LimitationPath _limitation;

    /**
     * Get the implicit to-many join path to the <code>eatlog.limitation</code>
     * table
     */
    public LimitationPath limitation() {
        if (_limitation == null)
            _limitation = new LimitationPath(this, null, Keys.LIMITATION_ACCOUNT_ACCOUNT_ID_FK.getInverseKey());

        return _limitation;
    }

    private transient StorePath _store;

    /**
     * Get the implicit to-many join path to the <code>eatlog.store</code> table
     */
    public StorePath store() {
        if (_store == null)
            _store = new StorePath(this, null, Keys.STORE_ACCOUNT_ACCOUNT_ID_FK.getInverseKey());

        return _store;
    }

    private transient WeightPath _weight;

    /**
     * Get the implicit to-many join path to the <code>eatlog.weight</code>
     * table
     */
    public WeightPath weight() {
        if (_weight == null)
            _weight = new WeightPath(this, null, Keys.WEIGHT_ACCOUNT_ACCOUNT_ID_FK.getInverseKey());

        return _weight;
    }

    @Override
    public Account as(String alias) {
        return new Account(DSL.name(alias), this);
    }

    @Override
    public Account as(Name alias) {
        return new Account(alias, this);
    }

    @Override
    public Account as(Table<?> alias) {
        return new Account(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Account rename(String name) {
        return new Account(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Account rename(Name name) {
        return new Account(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Account rename(Table<?> name) {
        return new Account(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Account where(Condition condition) {
        return new Account(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Account where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Account where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Account where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Account where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Account where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Account where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Account where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Account whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Account whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
