/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.eatlog.common.model.eatlog.tables;


import com.github.mbto.eatlog.common.model.eatlog.Eatlog;
import com.github.mbto.eatlog.common.model.eatlog.Indexes;
import com.github.mbto.eatlog.common.model.eatlog.Keys;
import com.github.mbto.eatlog.common.model.eatlog.tables.Product.ProductPath;
import com.github.mbto.eatlog.common.model.eatlog.tables.records.ConsumedRecord;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Consumed extends TableImpl<ConsumedRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>eatlog.consumed</code>
     */
    public static final Consumed CONSUMED = new Consumed();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ConsumedRecord> getRecordType() {
        return ConsumedRecord.class;
    }

    /**
     * The column <code>eatlog.consumed.id</code>.
     */
    public final TableField<ConsumedRecord, UInteger> ID = createField(DSL.name("id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>eatlog.consumed.date</code>.
     */
    public final TableField<ConsumedRecord, LocalDate> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>eatlog.consumed.product_id</code>.
     */
    public final TableField<ConsumedRecord, UInteger> PRODUCT_ID = createField(DSL.name("product_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>eatlog.consumed.gram</code>.
     */
    public final TableField<ConsumedRecord, Short> GRAM = createField(DSL.name("gram"), SQLDataType.SMALLINT.nullable(false), this, "");

    private Consumed(Name alias, Table<ConsumedRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Consumed(Name alias, Table<ConsumedRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>eatlog.consumed</code> table reference
     */
    public Consumed(String alias) {
        this(DSL.name(alias), CONSUMED);
    }

    /**
     * Create an aliased <code>eatlog.consumed</code> table reference
     */
    public Consumed(Name alias) {
        this(alias, CONSUMED);
    }

    /**
     * Create a <code>eatlog.consumed</code> table reference
     */
    public Consumed() {
        this(DSL.name("consumed"), null);
    }

    public <O extends Record> Consumed(Table<O> path, ForeignKey<O, ConsumedRecord> childPath, InverseForeignKey<O, ConsumedRecord> parentPath) {
        super(path, childPath, parentPath, CONSUMED);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ConsumedPath extends Consumed implements Path<ConsumedRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ConsumedPath(Table<O> path, ForeignKey<O, ConsumedRecord> childPath, InverseForeignKey<O, ConsumedRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ConsumedPath(Name alias, Table<ConsumedRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ConsumedPath as(String alias) {
            return new ConsumedPath(DSL.name(alias), this);
        }

        @Override
        public ConsumedPath as(Name alias) {
            return new ConsumedPath(alias, this);
        }

        @Override
        public ConsumedPath as(Table<?> alias) {
            return new ConsumedPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Eatlog.EATLOG;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.CONSUMED_DATE);
    }

    @Override
    public Identity<ConsumedRecord, UInteger> getIdentity() {
        return (Identity<ConsumedRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<ConsumedRecord> getPrimaryKey() {
        return Keys.KEY_CONSUMED_PRIMARY;
    }

    @Override
    public List<ForeignKey<ConsumedRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSUMED_PRODUCT_PRODUCT_ID_FK);
    }

    private transient ProductPath _product;

    /**
     * Get the implicit join path to the <code>eatlog.product</code> table.
     */
    public ProductPath product() {
        if (_product == null)
            _product = new ProductPath(this, Keys.CONSUMED_PRODUCT_PRODUCT_ID_FK, null);

        return _product;
    }

    @Override
    public Consumed as(String alias) {
        return new Consumed(DSL.name(alias), this);
    }

    @Override
    public Consumed as(Name alias) {
        return new Consumed(alias, this);
    }

    @Override
    public Consumed as(Table<?> alias) {
        return new Consumed(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Consumed rename(String name) {
        return new Consumed(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Consumed rename(Name name) {
        return new Consumed(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Consumed rename(Table<?> name) {
        return new Consumed(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Consumed where(Condition condition) {
        return new Consumed(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Consumed where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Consumed where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Consumed where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Consumed where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Consumed where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Consumed where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Consumed where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Consumed whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Consumed whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
