/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.eatlog.common.model.eatlog.tables;


import com.github.mbto.eatlog.common.model.eatlog.Eatlog;
import com.github.mbto.eatlog.common.model.eatlog.Indexes;
import com.github.mbto.eatlog.common.model.eatlog.Keys;
import com.github.mbto.eatlog.common.model.eatlog.tables.records.ConsumedRecord;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Consumed extends TableImpl<ConsumedRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>eatlog.consumed</code>
     */
    public static final Consumed CONSUMED = new Consumed();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ConsumedRecord> getRecordType() {
        return ConsumedRecord.class;
    }

    /**
     * The column <code>eatlog.consumed.id</code>.
     */
    public final TableField<ConsumedRecord, UInteger> ID = createField(DSL.name("id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>eatlog.consumed.date</code>.
     */
    public final TableField<ConsumedRecord, LocalDate> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>eatlog.consumed.product_id</code>.
     */
    public final TableField<ConsumedRecord, UInteger> PRODUCT_ID = createField(DSL.name("product_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>eatlog.consumed.gram</code>.
     */
    public final TableField<ConsumedRecord, Short> GRAM = createField(DSL.name("gram"), SQLDataType.SMALLINT.nullable(false), this, "");

    private Consumed(Name alias, Table<ConsumedRecord> aliased) {
        this(alias, aliased, null);
    }

    private Consumed(Name alias, Table<ConsumedRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>eatlog.consumed</code> table reference
     */
    public Consumed(String alias) {
        this(DSL.name(alias), CONSUMED);
    }

    /**
     * Create an aliased <code>eatlog.consumed</code> table reference
     */
    public Consumed(Name alias) {
        this(alias, CONSUMED);
    }

    /**
     * Create a <code>eatlog.consumed</code> table reference
     */
    public Consumed() {
        this(DSL.name("consumed"), null);
    }

    public <O extends Record> Consumed(Table<O> child, ForeignKey<O, ConsumedRecord> key) {
        super(child, key, CONSUMED);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Eatlog.EATLOG;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.CONSUMED_DATE);
    }

    @Override
    public Identity<ConsumedRecord, UInteger> getIdentity() {
        return (Identity<ConsumedRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<ConsumedRecord> getPrimaryKey() {
        return Keys.KEY_CONSUMED_PRIMARY;
    }

    @Override
    public List<ForeignKey<ConsumedRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSUMED_PRODUCT_PRODUCT_ID_FK);
    }

    private transient Product _product;

    /**
     * Get the implicit join path to the <code>eatlog.product</code> table.
     */
    public Product product() {
        if (_product == null)
            _product = new Product(this, Keys.CONSUMED_PRODUCT_PRODUCT_ID_FK);

        return _product;
    }

    @Override
    public Consumed as(String alias) {
        return new Consumed(DSL.name(alias), this);
    }

    @Override
    public Consumed as(Name alias) {
        return new Consumed(alias, this);
    }

    @Override
    public Consumed as(Table<?> alias) {
        return new Consumed(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Consumed rename(String name) {
        return new Consumed(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Consumed rename(Name name) {
        return new Consumed(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Consumed rename(Table<?> name) {
        return new Consumed(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<UInteger, LocalDate, UInteger, Short> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super UInteger, ? super LocalDate, ? super UInteger, ? super Short, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super UInteger, ? super LocalDate, ? super UInteger, ? super Short, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
