/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.eatlog.common.model.eatlog.tables;


import com.github.mbto.eatlog.common.model.eatlog.Eatlog;
import com.github.mbto.eatlog.common.model.eatlog.Keys;
import com.github.mbto.eatlog.common.model.eatlog.tables.Account.AccountPath;
import com.github.mbto.eatlog.common.model.eatlog.tables.records.LimitationRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Limitation extends TableImpl<LimitationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>eatlog.limitation</code>
     */
    public static final Limitation LIMITATION = new Limitation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LimitationRecord> getRecordType() {
        return LimitationRecord.class;
    }

    /**
     * The column <code>eatlog.limitation.id</code>.
     */
    public final TableField<LimitationRecord, UInteger> ID = createField(DSL.name("id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>eatlog.limitation.account_id</code>.
     */
    public final TableField<LimitationRecord, UInteger> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>eatlog.limitation.title</code>.
     */
    public final TableField<LimitationRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>eatlog.limitation.b</code>.
     */
    public final TableField<LimitationRecord, BigDecimal> B = createField(DSL.name("b"), SQLDataType.DECIMAL(5, 2), this, "");

    /**
     * The column <code>eatlog.limitation.j</code>.
     */
    public final TableField<LimitationRecord, BigDecimal> J = createField(DSL.name("j"), SQLDataType.DECIMAL(5, 2), this, "");

    /**
     * The column <code>eatlog.limitation.u</code>.
     */
    public final TableField<LimitationRecord, BigDecimal> U = createField(DSL.name("u"), SQLDataType.DECIMAL(5, 2), this, "");

    /**
     * The column <code>eatlog.limitation.b_to_kkal</code>.
     */
    public final TableField<LimitationRecord, BigDecimal> B_TO_KKAL = createField(DSL.name("b_to_kkal"), SQLDataType.DECIMAL(6, 2), this, "");

    /**
     * The column <code>eatlog.limitation.j_to_kkal</code>.
     */
    public final TableField<LimitationRecord, BigDecimal> J_TO_KKAL = createField(DSL.name("j_to_kkal"), SQLDataType.DECIMAL(6, 2), this, "");

    /**
     * The column <code>eatlog.limitation.u_to_kkal</code>.
     */
    public final TableField<LimitationRecord, BigDecimal> U_TO_KKAL = createField(DSL.name("u_to_kkal"), SQLDataType.DECIMAL(6, 2), this, "");

    private Limitation(Name alias, Table<LimitationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Limitation(Name alias, Table<LimitationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>eatlog.limitation</code> table reference
     */
    public Limitation(String alias) {
        this(DSL.name(alias), LIMITATION);
    }

    /**
     * Create an aliased <code>eatlog.limitation</code> table reference
     */
    public Limitation(Name alias) {
        this(alias, LIMITATION);
    }

    /**
     * Create a <code>eatlog.limitation</code> table reference
     */
    public Limitation() {
        this(DSL.name("limitation"), null);
    }

    public <O extends Record> Limitation(Table<O> path, ForeignKey<O, LimitationRecord> childPath, InverseForeignKey<O, LimitationRecord> parentPath) {
        super(path, childPath, parentPath, LIMITATION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class LimitationPath extends Limitation implements Path<LimitationRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> LimitationPath(Table<O> path, ForeignKey<O, LimitationRecord> childPath, InverseForeignKey<O, LimitationRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private LimitationPath(Name alias, Table<LimitationRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public LimitationPath as(String alias) {
            return new LimitationPath(DSL.name(alias), this);
        }

        @Override
        public LimitationPath as(Name alias) {
            return new LimitationPath(alias, this);
        }

        @Override
        public LimitationPath as(Table<?> alias) {
            return new LimitationPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Eatlog.EATLOG;
    }

    @Override
    public Identity<LimitationRecord, UInteger> getIdentity() {
        return (Identity<LimitationRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<LimitationRecord> getPrimaryKey() {
        return Keys.KEY_LIMITATION_PRIMARY;
    }

    @Override
    public List<ForeignKey<LimitationRecord, ?>> getReferences() {
        return Arrays.asList(Keys.LIMITATION_ACCOUNT_ACCOUNT_ID_FK);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>eatlog.account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.LIMITATION_ACCOUNT_ACCOUNT_ID_FK, null);

        return _account;
    }

    @Override
    public Limitation as(String alias) {
        return new Limitation(DSL.name(alias), this);
    }

    @Override
    public Limitation as(Name alias) {
        return new Limitation(alias, this);
    }

    @Override
    public Limitation as(Table<?> alias) {
        return new Limitation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Limitation rename(String name) {
        return new Limitation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Limitation rename(Name name) {
        return new Limitation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Limitation rename(Table<?> name) {
        return new Limitation(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Limitation where(Condition condition) {
        return new Limitation(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Limitation where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Limitation where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Limitation where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Limitation where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Limitation where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Limitation where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Limitation where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Limitation whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Limitation whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
