/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.eatlog.common.model.eatlog.tables;


import com.github.mbto.eatlog.common.model.eatlog.Eatlog;
import com.github.mbto.eatlog.common.model.eatlog.Keys;
import com.github.mbto.eatlog.common.model.eatlog.tables.Consumed.ConsumedPath;
import com.github.mbto.eatlog.common.model.eatlog.tables.Store.StorePath;
import com.github.mbto.eatlog.common.model.eatlog.tables.records.ProductRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * bju and kkal values: per 100 gram
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Product extends TableImpl<ProductRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>eatlog.product</code>
     */
    public static final Product PRODUCT = new Product();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductRecord> getRecordType() {
        return ProductRecord.class;
    }

    /**
     * The column <code>eatlog.product.id</code>.
     */
    public final TableField<ProductRecord, UInteger> ID = createField(DSL.name("id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>eatlog.product.store_id</code>.
     */
    public final TableField<ProductRecord, UInteger> STORE_ID = createField(DSL.name("store_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>eatlog.product.title</code>.
     */
    public final TableField<ProductRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>eatlog.product.portion_gram</code>.
     */
    public final TableField<ProductRecord, Short> PORTION_GRAM = createField(DSL.name("portion_gram"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>eatlog.product.b</code>.
     */
    public final TableField<ProductRecord, BigDecimal> B = createField(DSL.name("b"), SQLDataType.DECIMAL(5, 2).nullable(false), this, "");

    /**
     * The column <code>eatlog.product.j</code>.
     */
    public final TableField<ProductRecord, BigDecimal> J = createField(DSL.name("j"), SQLDataType.DECIMAL(5, 2).nullable(false), this, "");

    /**
     * The column <code>eatlog.product.u</code>.
     */
    public final TableField<ProductRecord, BigDecimal> U = createField(DSL.name("u"), SQLDataType.DECIMAL(5, 2).nullable(false), this, "");

    /**
     * The column <code>eatlog.product.b_to_kkal</code>.
     */
    public final TableField<ProductRecord, BigDecimal> B_TO_KKAL = createField(DSL.name("b_to_kkal"), SQLDataType.DECIMAL(6, 2).nullable(false), this, "");

    /**
     * The column <code>eatlog.product.j_to_kkal</code>.
     */
    public final TableField<ProductRecord, BigDecimal> J_TO_KKAL = createField(DSL.name("j_to_kkal"), SQLDataType.DECIMAL(6, 2).nullable(false), this, "");

    /**
     * The column <code>eatlog.product.u_to_kkal</code>.
     */
    public final TableField<ProductRecord, BigDecimal> U_TO_KKAL = createField(DSL.name("u_to_kkal"), SQLDataType.DECIMAL(6, 2).nullable(false), this, "");

    /**
     * The column <code>eatlog.product.kkal</code>.
     */
    public final TableField<ProductRecord, BigDecimal> KKAL = createField(DSL.name("kkal"), SQLDataType.DECIMAL(7, 2).nullable(false), this, "");

    private Product(Name alias, Table<ProductRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Product(Name alias, Table<ProductRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("bju and kkal values: per 100 gram"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>eatlog.product</code> table reference
     */
    public Product(String alias) {
        this(DSL.name(alias), PRODUCT);
    }

    /**
     * Create an aliased <code>eatlog.product</code> table reference
     */
    public Product(Name alias) {
        this(alias, PRODUCT);
    }

    /**
     * Create a <code>eatlog.product</code> table reference
     */
    public Product() {
        this(DSL.name("product"), null);
    }

    public <O extends Record> Product(Table<O> path, ForeignKey<O, ProductRecord> childPath, InverseForeignKey<O, ProductRecord> parentPath) {
        super(path, childPath, parentPath, PRODUCT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ProductPath extends Product implements Path<ProductRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ProductPath(Table<O> path, ForeignKey<O, ProductRecord> childPath, InverseForeignKey<O, ProductRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ProductPath(Name alias, Table<ProductRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ProductPath as(String alias) {
            return new ProductPath(DSL.name(alias), this);
        }

        @Override
        public ProductPath as(Name alias) {
            return new ProductPath(alias, this);
        }

        @Override
        public ProductPath as(Table<?> alias) {
            return new ProductPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Eatlog.EATLOG;
    }

    @Override
    public Identity<ProductRecord, UInteger> getIdentity() {
        return (Identity<ProductRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProductRecord> getPrimaryKey() {
        return Keys.KEY_PRODUCT_PRIMARY;
    }

    @Override
    public List<ForeignKey<ProductRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PRODUCT_STORE_STORE_ID_FK);
    }

    private transient StorePath _store;

    /**
     * Get the implicit join path to the <code>eatlog.store</code> table.
     */
    public StorePath store() {
        if (_store == null)
            _store = new StorePath(this, Keys.PRODUCT_STORE_STORE_ID_FK, null);

        return _store;
    }

    private transient ConsumedPath _consumed;

    /**
     * Get the implicit to-many join path to the <code>eatlog.consumed</code>
     * table
     */
    public ConsumedPath consumed() {
        if (_consumed == null)
            _consumed = new ConsumedPath(this, null, Keys.CONSUMED_PRODUCT_PRODUCT_ID_FK.getInverseKey());

        return _consumed;
    }

    @Override
    public Product as(String alias) {
        return new Product(DSL.name(alias), this);
    }

    @Override
    public Product as(Name alias) {
        return new Product(alias, this);
    }

    @Override
    public Product as(Table<?> alias) {
        return new Product(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Product rename(String name) {
        return new Product(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Product rename(Name name) {
        return new Product(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Product rename(Table<?> name) {
        return new Product(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Product where(Condition condition) {
        return new Product(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Product where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Product where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Product where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Product where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Product where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Product where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Product where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Product whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Product whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
