/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.eatlog.common.model.eatlog.tables;


import com.github.mbto.eatlog.common.model.eatlog.Eatlog;
import com.github.mbto.eatlog.common.model.eatlog.Keys;
import com.github.mbto.eatlog.common.model.eatlog.tables.records.SettingRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.TreeSet;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.jackson.extensions.converters.JSONtoJacksonConverter;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Setting extends TableImpl<SettingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>eatlog.setting</code>
     */
    public static final Setting SETTING = new Setting();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SettingRecord> getRecordType() {
        return SettingRecord.class;
    }

    /**
     * The column <code>eatlog.setting.id</code>.
     */
    public final TableField<SettingRecord, UInteger> ID = createField(DSL.name("id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>eatlog.setting.key</code>.
     */
    public final TableField<SettingRecord, String> KEY = createField(DSL.name("key"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>eatlog.setting.value</code>. string or json
     */
    public final TableField<SettingRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.CLOB, this, "string or json");

    /**
     * The column <code>eatlog.setting.roles</code>. json array with roles
     * names, example: ["owner","admin"]
     */
    public final TableField<SettingRecord, TreeSet<String>> ROLES = createField(DSL.name("roles"), SQLDataType.JSON, this, "json array with roles names, example: [\"owner\",\"admin\"]", new JSONtoJacksonConverter<TreeSet<String>>((Class<TreeSet<String>>) (Class) TreeSet.class));

    private Setting(Name alias, Table<SettingRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Setting(Name alias, Table<SettingRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>eatlog.setting</code> table reference
     */
    public Setting(String alias) {
        this(DSL.name(alias), SETTING);
    }

    /**
     * Create an aliased <code>eatlog.setting</code> table reference
     */
    public Setting(Name alias) {
        this(alias, SETTING);
    }

    /**
     * Create a <code>eatlog.setting</code> table reference
     */
    public Setting() {
        this(DSL.name("setting"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Eatlog.EATLOG;
    }

    @Override
    public Identity<SettingRecord, UInteger> getIdentity() {
        return (Identity<SettingRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<SettingRecord> getPrimaryKey() {
        return Keys.KEY_SETTING_PRIMARY;
    }

    @Override
    public List<UniqueKey<SettingRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SETTING_KEY);
    }

    @Override
    public Setting as(String alias) {
        return new Setting(DSL.name(alias), this);
    }

    @Override
    public Setting as(Name alias) {
        return new Setting(alias, this);
    }

    @Override
    public Setting as(Table<?> alias) {
        return new Setting(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Setting rename(String name) {
        return new Setting(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Setting rename(Name name) {
        return new Setting(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Setting rename(Table<?> name) {
        return new Setting(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Setting where(Condition condition) {
        return new Setting(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Setting where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Setting where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Setting where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Setting where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Setting where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Setting where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Setting where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Setting whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Setting whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
