/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.eatlog.common.model.eatlog.tables;


import com.github.mbto.eatlog.common.model.eatlog.Eatlog;
import com.github.mbto.eatlog.common.model.eatlog.Indexes;
import com.github.mbto.eatlog.common.model.eatlog.Keys;
import com.github.mbto.eatlog.common.model.eatlog.tables.Account.AccountPath;
import com.github.mbto.eatlog.common.model.eatlog.tables.Product.ProductPath;
import com.github.mbto.eatlog.common.model.eatlog.tables.records.StoreRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Store extends TableImpl<StoreRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>eatlog.store</code>
     */
    public static final Store STORE = new Store();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StoreRecord> getRecordType() {
        return StoreRecord.class;
    }

    /**
     * The column <code>eatlog.store.id</code>.
     */
    public final TableField<StoreRecord, UInteger> ID = createField(DSL.name("id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>eatlog.store.updated_at</code>.
     */
    public final TableField<StoreRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>eatlog.store.account_id</code>.
     */
    public final TableField<StoreRecord, UInteger> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>eatlog.store.title</code>.
     */
    public final TableField<StoreRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    private Store(Name alias, Table<StoreRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Store(Name alias, Table<StoreRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>eatlog.store</code> table reference
     */
    public Store(String alias) {
        this(DSL.name(alias), STORE);
    }

    /**
     * Create an aliased <code>eatlog.store</code> table reference
     */
    public Store(Name alias) {
        this(alias, STORE);
    }

    /**
     * Create a <code>eatlog.store</code> table reference
     */
    public Store() {
        this(DSL.name("store"), null);
    }

    public <O extends Record> Store(Table<O> path, ForeignKey<O, StoreRecord> childPath, InverseForeignKey<O, StoreRecord> parentPath) {
        super(path, childPath, parentPath, STORE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class StorePath extends Store implements Path<StoreRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> StorePath(Table<O> path, ForeignKey<O, StoreRecord> childPath, InverseForeignKey<O, StoreRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private StorePath(Name alias, Table<StoreRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public StorePath as(String alias) {
            return new StorePath(DSL.name(alias), this);
        }

        @Override
        public StorePath as(Name alias) {
            return new StorePath(alias, this);
        }

        @Override
        public StorePath as(Table<?> alias) {
            return new StorePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Eatlog.EATLOG;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.STORE_UPDATED_AT);
    }

    @Override
    public Identity<StoreRecord, UInteger> getIdentity() {
        return (Identity<StoreRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<StoreRecord> getPrimaryKey() {
        return Keys.KEY_STORE_PRIMARY;
    }

    @Override
    public List<ForeignKey<StoreRecord, ?>> getReferences() {
        return Arrays.asList(Keys.STORE_ACCOUNT_ACCOUNT_ID_FK);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>eatlog.account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.STORE_ACCOUNT_ACCOUNT_ID_FK, null);

        return _account;
    }

    private transient ProductPath _product;

    /**
     * Get the implicit to-many join path to the <code>eatlog.product</code>
     * table
     */
    public ProductPath product() {
        if (_product == null)
            _product = new ProductPath(this, null, Keys.PRODUCT_STORE_STORE_ID_FK.getInverseKey());

        return _product;
    }

    @Override
    public Store as(String alias) {
        return new Store(DSL.name(alias), this);
    }

    @Override
    public Store as(Name alias) {
        return new Store(alias, this);
    }

    @Override
    public Store as(Table<?> alias) {
        return new Store(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Store rename(String name) {
        return new Store(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Store rename(Name name) {
        return new Store(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Store rename(Table<?> name) {
        return new Store(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Store where(Condition condition) {
        return new Store(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Store where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Store where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Store where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Store where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Store where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Store where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Store where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Store whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Store whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
