/*
 * This file is generated by jOOQ.
 */
package com.github.mbto.eatlog.common.model.eatlog.tables;


import com.github.mbto.eatlog.common.model.eatlog.Eatlog;
import com.github.mbto.eatlog.common.model.eatlog.Indexes;
import com.github.mbto.eatlog.common.model.eatlog.Keys;
import com.github.mbto.eatlog.common.model.eatlog.tables.records.WeightRecord;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Weight extends TableImpl<WeightRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>eatlog.weight</code>
     */
    public static final Weight WEIGHT = new Weight();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WeightRecord> getRecordType() {
        return WeightRecord.class;
    }

    /**
     * The column <code>eatlog.weight.id</code>.
     */
    public final TableField<WeightRecord, UInteger> ID = createField(DSL.name("id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>eatlog.weight.date</code>.
     */
    public final TableField<WeightRecord, LocalDate> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>eatlog.weight.account_id</code>.
     */
    public final TableField<WeightRecord, UInteger> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>eatlog.weight.kilogram</code>.
     */
    public final TableField<WeightRecord, BigDecimal> KILOGRAM = createField(DSL.name("kilogram"), SQLDataType.DECIMAL(4, 1).nullable(false), this, "");

    private Weight(Name alias, Table<WeightRecord> aliased) {
        this(alias, aliased, null);
    }

    private Weight(Name alias, Table<WeightRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>eatlog.weight</code> table reference
     */
    public Weight(String alias) {
        this(DSL.name(alias), WEIGHT);
    }

    /**
     * Create an aliased <code>eatlog.weight</code> table reference
     */
    public Weight(Name alias) {
        this(alias, WEIGHT);
    }

    /**
     * Create a <code>eatlog.weight</code> table reference
     */
    public Weight() {
        this(DSL.name("weight"), null);
    }

    public <O extends Record> Weight(Table<O> child, ForeignKey<O, WeightRecord> key) {
        super(child, key, WEIGHT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Eatlog.EATLOG;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.WEIGHT_DATE);
    }

    @Override
    public Identity<WeightRecord, UInteger> getIdentity() {
        return (Identity<WeightRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<WeightRecord> getPrimaryKey() {
        return Keys.KEY_WEIGHT_PRIMARY;
    }

    @Override
    public List<ForeignKey<WeightRecord, ?>> getReferences() {
        return Arrays.asList(Keys.WEIGHT_ACCOUNT_ACCOUNT_ID_FK);
    }

    private transient Account _account;

    /**
     * Get the implicit join path to the <code>eatlog.account</code> table.
     */
    public Account account() {
        if (_account == null)
            _account = new Account(this, Keys.WEIGHT_ACCOUNT_ACCOUNT_ID_FK);

        return _account;
    }

    @Override
    public Weight as(String alias) {
        return new Weight(DSL.name(alias), this);
    }

    @Override
    public Weight as(Name alias) {
        return new Weight(alias, this);
    }

    @Override
    public Weight as(Table<?> alias) {
        return new Weight(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Weight rename(String name) {
        return new Weight(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Weight rename(Name name) {
        return new Weight(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Weight rename(Table<?> name) {
        return new Weight(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<UInteger, LocalDate, UInteger, BigDecimal> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super UInteger, ? super LocalDate, ? super UInteger, ? super BigDecimal, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super UInteger, ? super LocalDate, ? super UInteger, ? super BigDecimal, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
